# Generated by Django 2.0.2 on 2018-04-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_supplier_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Slug will be generated automatically from the title of the post', unique=True)),
                ('amount_paid', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Supplier')),
            ],
        ),
    ]
