# Generated by Django 2.0.2 on 2018-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_supplier_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug will be generated automatically from the title of the post', unique=True),
        ),
    ]
