# Generated by Django 2.0.2 on 2018-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180411_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the title of the post', unique=True),
        ),
        migrations.AlterField(
            model_name='supplier_ledger',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug will be generated automatically from the title of the post', unique=True),
        ),
    ]
