# Generated by Django 2.0.2 on 2018-04-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180415_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='slug',
        ),
    ]
