# Generated by Django 2.0.2 on 2018-04-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_supplier_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='author',
        ),
    ]
