# Generated by Django 2.0.2 on 2018-04-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_supplier_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='author',
        ),
    ]
