# Generated by Django 2.0.2 on 2018-04-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180416_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Customer'),
        ),
    ]
