# Generated by Django 2.0.2 on 2018-04-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180416_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bill',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
    ]
