# Generated by Django 2.0.2 on 2018-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_purchase_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='balance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
