# Generated by Django 2.0.2 on 2018-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_purchase_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='balance',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
    ]
