# Generated by Django 2.0.2 on 2018-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20180416_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_ledger',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
    ]
