# Generated by Django 2.0.2 on 2018-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20180416_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='balance',
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receivedAmount',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
    ]
