# Generated by Django 2.0.2 on 2018-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20180416_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
    ]
