# Generated by Django 2.0.2 on 2018-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20180416_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, max_length=200),
        ),
    ]
