# Generated by Django 2.0.2 on 2018-04-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20180417_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=200),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
