# Generated by Django 2.0.2 on 2018-04-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20180417_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
