# Generated by Django 2.0.2 on 2018-04-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180417_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
