# Generated by Django 2.0.2 on 2018-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20180417_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_value', models.CharField(default='2gt5w43w32', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, max_length=200),
        ),
    ]
