# Generated by Django 2.0.2 on 2018-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20180419_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
