# Generated by Django 2.0.2 on 2018-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_delete_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='tahir', max_length=200),
        ),
    ]
