# Generated by Django 2.0.2 on 2018-04-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_purchase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
    ]
