# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20180419_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, max_length=200),
        ),
    ]
