# Generated by Django 2.0.2 on 2018-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20180420_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receivedAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalBill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier_ledger',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
    ]
