# Generated by Django 2.0.2 on 2018-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_sale_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
    ]
