# Generated by Django 2.0.2 on 2018-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20180423_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receivedAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
    ]
