# Generated by Django 2.0.2 on 2018-04-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20180423_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_value', models.CharField(default='2gt5w43w32', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200)),
            ],
        ),
    ]
