# Generated by Django 2.0.2 on 2018-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='fix_value',
            field=models.CharField(default='2gt5w43w32', max_length=200),
        ),
    ]
