# Generated by Django 2.0.2 on 2018-04-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
