# Generated by Django 2.0.2 on 2018-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
    ]
