# Generated by Django 2.0.2 on 2018-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_purchase_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200),
        ),
    ]
