# Generated by Django 2.0.2 on 2018-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20180425_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, max_length=200, null=True),
        ),
    ]
