# Generated by Django 2.0.2 on 2018-04-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20180425_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='temp',
        ),
    ]
