# Generated by Django 2.0.2 on 2018-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20180426_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
    ]
