# Generated by Django 2.0.2 on 2018-04-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_remove_invoice_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
