# Generated by Django 2.0.2 on 2018-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
