# Generated by Django 2.0.2 on 2018-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=0, editable=False, max_length=200),
        ),
    ]
