# Generated by Django 2.0.2 on 2018-05-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
