# Generated by Django 2.0.2 on 2018-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20180511_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=200),
        ),
    ]
