# Generated by Django 2.0.2 on 2018-05-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_auto_20180512_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale_product',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sale'),
        ),
    ]
