# Generated by Django 2.0.2 on 2018-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_auto_20180517_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_product',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=200),
        ),
    ]
