# Generated by Django 2.0.2 on 2018-05-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0080_sale_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fix_value',
            field=models.CharField(default='2532', max_length=200),
        ),
    ]
