# Generated by Django 2.0.2 on 2018-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_auto_20180517_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='balance',
        ),
        migrations.AddField(
            model_name='sale_product',
            name='barcode',
            field=models.CharField(default=2332, max_length=200),
            preserve_default=False,
        ),
    ]
