# Generated by Django 2.0.2 on 2018-05-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_auto_20180517_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_product',
            name='barcode',
            field=models.IntegerField(),
        ),
    ]
